import { NAME } from './commentConstants';

export const FETCH_COMMENTS_REQUEST = `${NAME}/FETCH_COMMENTS_REQUEST`;
export type FETCH_COMMENTS_REQUEST = typeof FETCH_COMMENTS_REQUEST;

export const FETCH_COMMENTS_SUCCESS = `${NAME}/FETCH_COMMENTS_SUCCESS`;
export type FETCH_COMMENTS_SUCCESS = typeof FETCH_COMMENTS_SUCCESS;

export const FETCH_COMMENTS_FAIL = `${NAME}/FETCH_COMMENTS_FAIL`;
export type FETCH_COMMENTS_FAIL = typeof FETCH_COMMENTS_FAIL;