import { NAME } from "./postConstants";

export const FETCH_POSTS_REQUEST = `${NAME}/FETCH_POSTS_REQUEST`;
export type FETCH_POSTS_REQUEST = typeof FETCH_POSTS_REQUEST;

export const FETCH_POSTS_SUCCESS = `${NAME}/FETCH_POSTS_SUCCESS`;
export type FETCH_POSTS_SUCCESS = typeof FETCH_POSTS_SUCCESS;

export const FETCH_POSTS_FAIL = `${NAME}/FETCH_POSTS_FAIL`;
export type FETCH_POSTS_FAIL = typeof FETCH_POSTS_FAIL;

export const ADD_POST_REQUEST = `${NAME}/ADD_POST_REQUEST`;
export type ADD_POST_REQUEST = typeof ADD_POST_REQUEST;

export const ADD_POST_SUCCESS = `${NAME}/ADD_POST_SUCCESS`;
export type ADD_POST_SUCCESS = typeof ADD_POST_SUCCESS;

export const ADD_POST_FAIL = `${NAME}/ADD_POST_FAIL`;
export type ADD_POST_FAIL = typeof ADD_POST_FAIL;

export const UPDATE_POST_REQUEST = `${NAME}/UPDATE_POST_REQUEST`;
export type UPDATE_POST_REQUEST = typeof UPDATE_POST_REQUEST;

export const UPDATE_POST_SUCCESS = `${NAME}/UPDATE_POST_SUCCESS`;
export type UPDATE_POST_SUCCESS = typeof UPDATE_POST_SUCCESS;

export const UPDATE_POST_FAIL = `${NAME}/UPDATE_POST_FAIL`;
export type UPDATE_POST_FAIL = typeof UPDATE_POST_FAIL;

export const DELETE_POST_REQUEST = `${NAME}/DELETE_POST_REQUEST`;
export type DELETE_POST_REQUEST = typeof DELETE_POST_REQUEST;

export const DELETE_POST_SUCCESS = `${NAME}/DELETE_POST_SUCCESS`;
export type DELETE_POST_SUCCESS = typeof DELETE_POST_SUCCESS;

export const DELETE_POST_FAIL = `${NAME}/DELETE_POST_FAIL`;
export type DELETE_POST_FAIL = typeof DELETE_POST_FAIL;
