import { NAME } from './authConstants';

export const LOGIN_USER_REQUEST = `${NAME}/LOGIN_USER_REQUEST`;
export type LOGIN_USER_REQUEST = typeof LOGIN_USER_REQUEST;

export const LOGIN_USER_SUCCESS = `${NAME}/LOGIN_USER_SUCCESS`;
export type LOGIN_USER_SUCCESS = typeof LOGIN_USER_SUCCESS;

export const LOGIN_USER_FAIL = `${NAME}/LOGIN_USER_FAIL`;
export type LOGIN_USER_FAIL = typeof LOGIN_USER_FAIL;

export const REGISTER_USER_REQUEST = `${NAME}/REGISTER_USER_REQUEST`;
export type REGISTER_USER_REQUEST = typeof REGISTER_USER_REQUEST;

export const REGISTER_USER_SUCCESS = `${NAME}/REGISTER_USER_SUCCESS`;
export type REGISTER_USER_SUCCESS = typeof REGISTER_USER_SUCCESS;

export const REGISTER_USER_FAIL = `${NAME}/REGISTER_USER_FAIL`;
export type REGISTER_USER_FAIL = typeof REGISTER_USER_FAIL;
